update to c11, fix #34
to fix build error:
```
gcc -g -Wall -std=c99 -Wwrite-strings -funroll-loops -Wstrict-prototypes -I. -Iinclude -fPIC -Ofast -DSVD_ACTIVATED=1 -DCTRLC=1  -DCOPYAMATRIX=1  -DLAPACK_LIB_FOUND -DUSE_LAPACK -c src/scs.c -o out/obj/scs.o
In file included from include/scs.h:36,
                 from src/scs.c:28:
include/util.h:78:25: error: field 'tic' has incomplete type
   78 |         struct timespec tic;
      |                         ^~~
include/util.h:79:25: error: field 'toc' has incomplete type
   79 |         struct timespec toc;
      |                         ^~~
make: *** [Makefile:59: out/obj/scs.o] Error 1
```